

name: Run Preprocessing on Push

on:
  push:
    branches:
      - main    
      - master
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest # Server Ubuntu

    steps:
    - name: 1. Checkout Repository
      uses: actions/checkout@v4

    - name: 2. Setup Python 3.12.7
      # Menggunakan action resmi GitHub (pasti ditemukan)
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.7" # Versi Python
     

    - name: 3. Install Dependencies (via pip)
      run: |
        python -m pip install --upgrade pip
        # Instal library yang dibutuhkan skrip Anda
        pip install pandas scikit-learn numpy

    - name: 4. Run Preprocessing Script
      run: |
       
        python preprocessing/automate_Muhammad-Rozagi.py

    - name: 5. Upload Preprocessed Dataset as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: processed-heart-dataset
        path: preprocessing/heart_preprocessing/heart_preprocessed.csv
        retention-days: 7
